# Example KiBot config file
kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC (LCSC) code'
    type: generic
    include_only:
      - column: 'LCSC#'
        regex: '^C\d+'

preflight:
  set_text_variables:
    - name: "MYVAR"
      text: "tests/data"

variants:
  - name: rotated
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint

outputs:
  - name: classic_netlist
    comment: Schematic netlist in KiCad format
    type: netlist
    dir: Export
    
  - name: 'Costs'
    comment: "Components costs spreadsheet"
    type: kicost
    dir: KiCost
    options:
      output: 'multipart'
      no_collapse: true
      number: 1000
      no_price: true
      translate_fields:
        - field: fabricante
          name: manf
      aggregate:
        - file: tests/data/multipart2.xml
          number: 1000

  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: Schematic.pdf

  - name: Step
    comment: "Generate 3D model (STEP)"
    type: step
    dir: 3D
    options:
      metric_units: false
      origin: "3.2,-10"    # "grid" or "drill" o "X,Y" i.e. 3.2,-10
      no_virtual: true     # exclude 3D models for components with 'virtual' attribute
      min_distance: 0.0004 # Minimum distance between points to treat them as separate ones (default 0.01 mm)
      #output: project.step

  - name: 'interactive_bom'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: BoM
    options:
      hide_pads: false
      show_fabrication: false
      hide_silkscreen: false
      highlight_pin1: false
      no_redraw_on_drag: false
      board_rotation: 0
      checkboxes: 'Sourced,Placed'
      bom_view: 'left-right'
      layer_view: 'FB'
      name_format: '%f_iBoM'
      output: ''
      include_tracks: false
      include_nets: false
      sort_order: 'C,R,L,D,U,Y,X,F,SW,A,~,HS,CNN,J,P,NT,MH'
      blacklist: 'DNF*'
      no_blacklist_virtual: false
      blacklist_empty_val: false
      netlist_file: ''
      extra_fields: ''
      normalize_field_case: false
      variant_field: ''
      variants_whitelist: ''
      variants_blacklist: ''
      dnp_field: ''

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: JLCPCB
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
      inner_extension_pattern: '.gp%n'
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - In1.Cu
      - In2.Cu
      - In3.Cu
      - In4.Cu
      - In5.Cu
      - In6.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: JLCPCB
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: 'JLCPCB_position'
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: JLCPCB
    options:
      variant: rotated
      output: '%f_cpl_jlc.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: 'JLCPCB_bom'
    comment: "BoM for JLCPCB"
    type: bom
    dir: JLCPCB
    options:
      output: '%f_%i_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC#'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /
        - from_output: JLCPCB_position
          dest: /
        - from_output: JLCPCB_bom
          dest: /